version: '3.8'

services:
  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    ports:
      - 9042:9042
    environment:
      CASSANDRA_CLUSTER_NAME: "Cassandra_cluster"
      CASSANDRA_AUTHENTICATOR: "PasswordAuthenticator"
      CASSANDRA_USERNAME: "admin"
      CASSANDRA_PASSWORD: "admin"
      CASSANDRA_RPC_ADDRESS: 0.0.0.0
      CASSANDRA_NATIVE_TRANSPORT_PORT: 9042
    volumes:
      - ./data/cassandra_data:/var/lib/cassandra
    networks:
      - cassandra_net

  redis:
      image: redis:7
      container_name: redis
      restart: always
      ports:
        - "6379:6379"

networks:
  cassandra_net:
    name: "cassandra_net"
    driver: bridge