version: '3.8'

services:
  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    ports:
      - 9042:9042
    environment:
      CASSANDRA_CLUSTER_NAME: "Cassandra_cluster"
      CASSANDRA_AUTHENTICATOR: "PasswordAuthenticator"
      CASSANDRA_USERNAME: "admin"
      CASSANDRA_PASSWORD: "admin"
    volumes:
      - ./data/cassandra_data:/var/lib/cassandra
    networks:
      - cassandra_net

networks:
  cassandra_net:
    name: "cassandra_net"
    driver: bridge