from enum import Enum
from pydantic import BaseModel
from typing import Union


class ErrorModel(BaseModel):
    detail: Union[str, dict[str, str]]


class ErrorMessages(str, Enum):
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_INVALID_PASSWORD = "UPDATE_USER_INVALID_PASSWORD"
    USER_INVALID_CURRENT_PASSWORD = "USER_INVALID_CURRENT_PASSWORD"
    LOGIN_BAD_CREDENTIALS = "LOGIN_BAD_CREDENTIALS"
    LOGIN_USER_NOT_VERIFIED = "LOGIN_USER_NOT_VERIFIED"
    RESET_PASSWORD_BAD_TOKEN = "RESET_PASSWORD_BAD_TOKEN"
    RESET_PASSWORD_INVALID_PASSWORD = "RESET_PASSWORD_INVALID_PASSWORD"
    VERIFY_USER_BAD_TOKEN = "VERIFY_USER_BAD_TOKEN"
    MISSING_TOKEN_OR_USER_IS_NOT_ACTIVE = "MISSING_TOKEN_OR_USER_IS_NOT_ACTIVE"
    NOT_AUTHORIZED = "NOT_AUTHORIZED"
    UNAUTHORIZED = "UNAUTHORIZED"
